data_dir: data
model_assets_dir: model_assets

features:
  data_dir: ./data
  train_size: 0.8
  vectoriser_name: tfidf_vectoriser
  vectoriser_args:
    min_df: 3
    max_df: 0.3
    stop_words: "english"
    ngram_range: [1, 3]
  scaler_name: "minmax_scaler"

model:
  model_name: lr
  model_params:
    max_iter: 10000
    random_state: 42
